/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSafetyRouteImport } from './routes/_authenticated/safety'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedLostFoundRouteImport } from './routes/_authenticated/lost-found'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComplaintsRouteImport } from './routes/_authenticated/complaints'
import { Route as AuthenticatedCleaningRouteImport } from './routes/_authenticated/cleaning'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedLostFoundIndexRouteImport } from './routes/_authenticated/lost-found.index'
import { Route as AuthenticatedComplaintsIndexRouteImport } from './routes/_authenticated/complaints.index'
import { Route as AuthenticatedReportCodeRouteImport } from './routes/_authenticated/report.$code'
import { Route as AuthenticatedLostFoundNewRouteImport } from './routes/_authenticated/lost-found.new'
import { Route as AuthenticatedComplaintsNewRouteImport } from './routes/_authenticated/complaints.new'
import { Route as AuthenticatedComplaintsIdRouteImport } from './routes/_authenticated/complaints.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSafetyRoute = AuthenticatedSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLostFoundRoute = AuthenticatedLostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplaintsRoute = AuthenticatedComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCleaningRoute = AuthenticatedCleaningRouteImport.update({
  id: '/cleaning',
  path: '/cleaning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLostFoundIndexRoute =
  AuthenticatedLostFoundIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLostFoundRoute,
  } as any)
const AuthenticatedComplaintsIndexRoute =
  AuthenticatedComplaintsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedComplaintsRoute,
  } as any)
const AuthenticatedReportCodeRoute = AuthenticatedReportCodeRouteImport.update({
  id: '/report/$code',
  path: '/report/$code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLostFoundNewRoute =
  AuthenticatedLostFoundNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedLostFoundRoute,
  } as any)
const AuthenticatedComplaintsNewRoute =
  AuthenticatedComplaintsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedComplaintsRoute,
  } as any)
const AuthenticatedComplaintsIdRoute =
  AuthenticatedComplaintsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedComplaintsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/cleaning': typeof AuthenticatedCleaningRoute
  '/complaints': typeof AuthenticatedComplaintsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lost-found': typeof AuthenticatedLostFoundRouteWithChildren
  '/resources': typeof AuthenticatedResourcesRoute
  '/safety': typeof AuthenticatedSafetyRoute
  '/users': typeof AuthenticatedUsersRoute
  '/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/complaints/new': typeof AuthenticatedComplaintsNewRoute
  '/lost-found/new': typeof AuthenticatedLostFoundNewRoute
  '/report/$code': typeof AuthenticatedReportCodeRoute
  '/complaints/': typeof AuthenticatedComplaintsIndexRoute
  '/lost-found/': typeof AuthenticatedLostFoundIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/cleaning': typeof AuthenticatedCleaningRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/safety': typeof AuthenticatedSafetyRoute
  '/users': typeof AuthenticatedUsersRoute
  '/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/complaints/new': typeof AuthenticatedComplaintsNewRoute
  '/lost-found/new': typeof AuthenticatedLostFoundNewRoute
  '/report/$code': typeof AuthenticatedReportCodeRoute
  '/complaints': typeof AuthenticatedComplaintsIndexRoute
  '/lost-found': typeof AuthenticatedLostFoundIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/cleaning': typeof AuthenticatedCleaningRoute
  '/_authenticated/complaints': typeof AuthenticatedComplaintsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lost-found': typeof AuthenticatedLostFoundRouteWithChildren
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/safety': typeof AuthenticatedSafetyRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/_authenticated/complaints/new': typeof AuthenticatedComplaintsNewRoute
  '/_authenticated/lost-found/new': typeof AuthenticatedLostFoundNewRoute
  '/_authenticated/report/$code': typeof AuthenticatedReportCodeRoute
  '/_authenticated/complaints/': typeof AuthenticatedComplaintsIndexRoute
  '/_authenticated/lost-found/': typeof AuthenticatedLostFoundIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/announcements'
    | '/cleaning'
    | '/complaints'
    | '/dashboard'
    | '/lost-found'
    | '/resources'
    | '/safety'
    | '/users'
    | '/complaints/$id'
    | '/complaints/new'
    | '/lost-found/new'
    | '/report/$code'
    | '/complaints/'
    | '/lost-found/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/announcements'
    | '/cleaning'
    | '/dashboard'
    | '/resources'
    | '/safety'
    | '/users'
    | '/complaints/$id'
    | '/complaints/new'
    | '/lost-found/new'
    | '/report/$code'
    | '/complaints'
    | '/lost-found'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/announcements'
    | '/_authenticated/cleaning'
    | '/_authenticated/complaints'
    | '/_authenticated/dashboard'
    | '/_authenticated/lost-found'
    | '/_authenticated/resources'
    | '/_authenticated/safety'
    | '/_authenticated/users'
    | '/_authenticated/complaints/$id'
    | '/_authenticated/complaints/new'
    | '/_authenticated/lost-found/new'
    | '/_authenticated/report/$code'
    | '/_authenticated/complaints/'
    | '/_authenticated/lost-found/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/safety': {
      id: '/_authenticated/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof AuthenticatedSafetyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lost-found': {
      id: '/_authenticated/lost-found'
      path: '/lost-found'
      fullPath: '/lost-found'
      preLoaderRoute: typeof AuthenticatedLostFoundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complaints': {
      id: '/_authenticated/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AuthenticatedComplaintsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cleaning': {
      id: '/_authenticated/cleaning'
      path: '/cleaning'
      fullPath: '/cleaning'
      preLoaderRoute: typeof AuthenticatedCleaningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lost-found/': {
      id: '/_authenticated/lost-found/'
      path: '/'
      fullPath: '/lost-found/'
      preLoaderRoute: typeof AuthenticatedLostFoundIndexRouteImport
      parentRoute: typeof AuthenticatedLostFoundRoute
    }
    '/_authenticated/complaints/': {
      id: '/_authenticated/complaints/'
      path: '/'
      fullPath: '/complaints/'
      preLoaderRoute: typeof AuthenticatedComplaintsIndexRouteImport
      parentRoute: typeof AuthenticatedComplaintsRoute
    }
    '/_authenticated/report/$code': {
      id: '/_authenticated/report/$code'
      path: '/report/$code'
      fullPath: '/report/$code'
      preLoaderRoute: typeof AuthenticatedReportCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lost-found/new': {
      id: '/_authenticated/lost-found/new'
      path: '/new'
      fullPath: '/lost-found/new'
      preLoaderRoute: typeof AuthenticatedLostFoundNewRouteImport
      parentRoute: typeof AuthenticatedLostFoundRoute
    }
    '/_authenticated/complaints/new': {
      id: '/_authenticated/complaints/new'
      path: '/new'
      fullPath: '/complaints/new'
      preLoaderRoute: typeof AuthenticatedComplaintsNewRouteImport
      parentRoute: typeof AuthenticatedComplaintsRoute
    }
    '/_authenticated/complaints/$id': {
      id: '/_authenticated/complaints/$id'
      path: '/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof AuthenticatedComplaintsIdRouteImport
      parentRoute: typeof AuthenticatedComplaintsRoute
    }
  }
}

interface AuthenticatedComplaintsRouteChildren {
  AuthenticatedComplaintsIdRoute: typeof AuthenticatedComplaintsIdRoute
  AuthenticatedComplaintsNewRoute: typeof AuthenticatedComplaintsNewRoute
  AuthenticatedComplaintsIndexRoute: typeof AuthenticatedComplaintsIndexRoute
}

const AuthenticatedComplaintsRouteChildren: AuthenticatedComplaintsRouteChildren =
  {
    AuthenticatedComplaintsIdRoute: AuthenticatedComplaintsIdRoute,
    AuthenticatedComplaintsNewRoute: AuthenticatedComplaintsNewRoute,
    AuthenticatedComplaintsIndexRoute: AuthenticatedComplaintsIndexRoute,
  }

const AuthenticatedComplaintsRouteWithChildren =
  AuthenticatedComplaintsRoute._addFileChildren(
    AuthenticatedComplaintsRouteChildren,
  )

interface AuthenticatedLostFoundRouteChildren {
  AuthenticatedLostFoundNewRoute: typeof AuthenticatedLostFoundNewRoute
  AuthenticatedLostFoundIndexRoute: typeof AuthenticatedLostFoundIndexRoute
}

const AuthenticatedLostFoundRouteChildren: AuthenticatedLostFoundRouteChildren =
  {
    AuthenticatedLostFoundNewRoute: AuthenticatedLostFoundNewRoute,
    AuthenticatedLostFoundIndexRoute: AuthenticatedLostFoundIndexRoute,
  }

const AuthenticatedLostFoundRouteWithChildren =
  AuthenticatedLostFoundRoute._addFileChildren(
    AuthenticatedLostFoundRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedCleaningRoute: typeof AuthenticatedCleaningRoute
  AuthenticatedComplaintsRoute: typeof AuthenticatedComplaintsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLostFoundRoute: typeof AuthenticatedLostFoundRouteWithChildren
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedSafetyRoute: typeof AuthenticatedSafetyRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedReportCodeRoute: typeof AuthenticatedReportCodeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedCleaningRoute: AuthenticatedCleaningRoute,
  AuthenticatedComplaintsRoute: AuthenticatedComplaintsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLostFoundRoute: AuthenticatedLostFoundRouteWithChildren,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedSafetyRoute: AuthenticatedSafetyRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedReportCodeRoute: AuthenticatedReportCodeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
